<?php
if ( ! defined( "ABSPATH" ) ) exit;

/**
 * Title: Hero Section
 * Slug: themekickstarter/hero
 * Categories: themekickstarter
 * Description: Full-width cover hero with a background image, headline, and button.
 */
?>
<!-- wp:cover {"dimRatio":40,"minHeight":60,"minHeightUnit":"vh","align":"full","className":"pts-hero-full-width pts-animate-hero","layout":{"type":"constrained"}} -->
<div class="wp-block-cover alignfull pts-hero-full-width pts-animate-hero" style="min-height:60vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-40 has-background-dim"></span><div class="wp-block-cover__inner-container">
    <!-- wp:heading {"textAlign":"center","level":1,"className":"pts-animate-hero__item text-white"} -->
    <h1 class="wp-block-heading has-text-align-center pts-animate-hero__item text-white">Welcome to Our Amazing Website</h1>
    <!-- /wp:heading -->

    <!-- wp:paragraph {"align":"center","className":"pts-animate-hero__item text-white"} -->
    <p class="has-text-align-center pts-animate-hero__item text-white">This is a hero section generated by Picot Theme Seeder. Replace the cover background image from the block toolbar.</p>
    <!-- /wp:paragraph -->

    <!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"},"className":"pts-animate-hero__item"} -->
    <div class="wp-block-buttons pts-animate-hero__item">
        <!-- wp:button -->
        <div class="wp-block-button"><a class="wp-block-button__link wp-element-button btn btn-light">Get Started</a></div>
        <!-- /wp:button -->
    </div>
    <!-- /wp:buttons -->
</div></div>
<!-- /wp:cover -->
